#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Example ./0-transfer_file 1-install_load_balancer 35.175.132.181 ubuntu /~/.ssh/id_rsa.pub

if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 3 ]
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
