#!/usr/bin/env bash
# A bash Script that configure HAproxy so that it send trafic to 2 servers
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*
echo "
    frontend http_front
        bind *:80
        mode http
        default_backend web_back

    backend web_back
        mode http
        balance roundrobin
        server 293414-web-01 54.146.74.212:80 check
        server 293414-web-02 18.207.139.48:80 check
    " >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo service haproxy restart
