#!/usr/bin/env bash
# This script is displaying the numbers from 1 - 100
# multiples of 3 and 5 for fizzbuzz
# multiples of 3 for fizz and 5 for buzz
for ((i = 1; i <= 100; i++))
do
	if ((i % 3 == 0)) && ((i % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
