#!/usr/bin/env bash
# A bash script that configures container so nginx is running as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
